var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/binnacle-app/auth/callback/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c470e835._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_186e8fef._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fe06900a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_layout_tsx_271801d7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_binnacle-app_auth_callback_page_actions_fe5dd3df.js")
R.m(1261)
module.exports=R.m(1261).exports
