#!/usr/bin/env node

/**
 * Downloads images and converts them to ASCII art.
 * Outputs app/data/ascii-art.ts with all pieces ready for the animation.
 *
 * Usage:
 *   node scripts/generate-ascii.js
 *
 * Sources support: { url: '...' } or { file: './local.jpg' }
 * Requires: sharp (npm install --save-dev sharp)
 */

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

// --- Config ---
const GRID_WIDTH = 130;
const GRID_HEIGHT = 60; // 16:9 with char cell aspect ratio ~0.825
const GRADIENT = ' .:-=+*%#@'; // lightest → darkest (10 chars)

const SOURCES = [
  {
    url: 'https://upload.wikimedia.org/wikipedia/commons/6/60/1973_Citroen_DS_2.0_Side.jpg',
    label: '1973 citroen ds',
  },
  {
    url: 'https://images.pexels.com/photos/1425146/pexels-photo-1425146.jpeg?auto=compress&cs=tinysrgb&w=1920',
    label: 'vintage typewriter',
  },
  {
    url: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Teenage_Engineering_Pocket_Operators_-_PO-14_sub_%26_stock_cartons_-_2015_NAMM_Show.jpg',
    label: 'pocket operator',
  },
  {
    url: 'https://images.pexels.com/photos/821738/pexels-photo-821738.jpeg?auto=compress&cs=tinysrgb&w=1920',
    label: 'hasselblad 500c',
  },
  {
    url: 'https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=1920',
    label: 'porsche 911',
  },
];

const FETCH_DELAY_MS = 1500; // avoid rate limits on Wikimedia
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// --- Image → ASCII ---
async function imageToAscii(buffer) {
  const pixels = await sharp(buffer)
    .resize(GRID_WIDTH, GRID_HEIGHT, { fit: 'cover', position: 'centre' })
    .grayscale()
    .normalise()
    .raw()
    .toBuffer();

  const lines = [];
  for (let r = 0; r < GRID_HEIGHT; r++) {
    let line = '';
    for (let c = 0; c < GRID_WIDTH; c++) {
      const brightness = pixels[r * GRID_WIDTH + c];
      // Invert: dark pixels → dense chars, bright pixels → light chars
      const idx = Math.round((1 - brightness / 255) * (GRADIENT.length - 1));
      line += GRADIENT[idx];
    }
    lines.push(line);
  }
  return lines;
}

// --- Generate TypeScript output ---
function generateTS(pieces) {
  let ts = '// Auto-generated by scripts/generate-ascii.js — do not edit by hand\n\n';
  ts += `export const GRID_WIDTH = ${GRID_WIDTH};\n`;
  ts += `export const GRID_HEIGHT = ${GRID_HEIGHT};\n\n`;

  ts += `function pad(lines: string[]): string[] {\n`;
  ts += `  return Array.from({ length: GRID_HEIGHT }, (_, i) =>\n`;
  ts += `    (lines[i] || '').padEnd(GRID_WIDTH).slice(0, GRID_WIDTH)\n`;
  ts += `  );\n`;
  ts += `}\n\n`;

  const varNames = [];
  for (let i = 0; i < pieces.length; i++) {
    const varName = `ART_${i}_RAW`;
    varNames.push(varName);
    ts += `const ${varName} = \`${pieces[i].lines.join('\n')}\`.split('\\n');\n\n`;
  }

  ts += `export const ART_PIECES = [\n`;
  for (const name of varNames) {
    ts += `  pad(${name}),\n`;
  }
  ts += `];\n\n`;

  ts += `export const LABELS = [\n`;
  for (const piece of pieces) {
    ts += `  '${piece.label.replace(/'/g, "\\'")}',\n`;
  }
  ts += `];\n`;

  return ts;
}

// --- Main ---
async function main() {
  console.log(`Generating ASCII art (${GRID_WIDTH}×${GRID_HEIGHT}, ${SOURCES.length} pieces)...\n`);

  const pieces = [];

  for (const src of SOURCES) {
    console.log(`[${pieces.length + 1}/${SOURCES.length}] "${src.label}"`);

    let buffer;
    if (src.file) {
      buffer = fs.readFileSync(path.resolve(src.file));
      console.log(`  Local file: ${src.file}`);
    } else if (src.url) {
      console.log(`  Downloading: ${src.url.slice(0, 80)}...`);
      if (pieces.length > 0) await sleep(FETCH_DELAY_MS);
      const res = await fetch(src.url, {
        headers: { 'User-Agent': 'leonjacobs-site-ascii-gen/1.0' },
      });
      if (!res.ok) {
        throw new Error(`Failed to download (${res.status}): ${src.url}`);
      }
      buffer = Buffer.from(await res.arrayBuffer());
    } else {
      throw new Error(`Source "${src.label}" needs either a "url" or "file" property`);
    }

    const lines = await imageToAscii(buffer);
    pieces.push({ label: src.label, lines });
    console.log(`  Done.\n`);
  }

  const outPath = path.join(__dirname, '..', 'app', 'data', 'ascii-art.ts');
  fs.writeFileSync(outPath, generateTS(pieces));
  console.log(`Wrote ${pieces.length} pieces to ${outPath}`);
}

main().catch((err) => {
  console.error('Error:', err.message);
  process.exit(1);
});
